# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Install tox
      - run:
          name: install tox
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install tox

      # Run tests
      - run:
          name: run tests
          command: |
            . ~/venv/bin/activate
            tox -v

      - store_artifacts:
          path: test-reports
          destination: test-reports
